In [1]:
import sys

# Check if running in a Jupyter notebook
if 'ipykernel_launcher' in sys.argv[0]:
    sys.argv = sys.argv[:1]

# Now import the train_detection.py file
sys.path.append("/")
from train_detection import *

/home/yu/anaconda3/envs/torch_env/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
print(data_path)

data/Detection_Passive.pkl


In [3]:
print("hello world")
# print the python location
print(sys.executable)
# print the location of the script
print(sys.argv[0])
# print hello world
print("hello world")

hello world
/home/yu/anaconda3/envs/torch_env/bin/python3.9
/home/yu/anaconda3/envs/torch_env/lib/python3.9/site-packages/ipykernel_launcher.py
hello world


In [4]:
data_x, data_y, data_subj = load_pickle("data/Detection_Passive.pkl")

In [5]:
type(data_x)

numpy.ndarray

In [6]:
data_y[0]

array([0, 0, 0, ..., 0, 0, 0])

In [8]:
# show all the different values in data_y[0]
import numpy as np
np.unique(data_y[0], return_counts=True)


(array([0, 1]), array([68170, 14760]))

In [5]:
data_x.size

21

In [13]:
type(data_x[0])

numpy.ndarray

In [14]:
# show the range for the data in the data_x
data_x[0].min(), data_x[0].max()

(0.018045718, 0.9859759)

In [6]:
data_x.shape

(21,)

In [7]:
data_y.shape

(21,)

In [8]:
data_subj.shape

(21,)

In [9]:
train_subjects, val_subjects, test_subjects = load_split(args.split)

train_dataset = DetectionDataset(data_x, data_y, data_subj, train_subjects)
val_dataset = DetectionDataset(data_x, data_y, data_subj, val_subjects)
test_dataset = DetectionDataset(data_x, data_y, data_subj, test_subjects)

In [10]:
# print the first item in the train_dataset
train_dataset[0]

(array([[0.49099624, 0.49136534, 0.53177553, 0.49296564, 0.5030023 ,
         0.51033264],
        [0.4908631 , 0.4911624 , 0.53171724, 0.4934174 , 0.5025291 ,
         0.5093043 ],
        [0.4904063 , 0.491051  , 0.53172296, 0.49324882, 0.501987  ,
         0.50812936],
        ...,
        [0.4818431 , 0.511539  , 0.51523894, 0.5246649 , 0.48808447,
         0.5082532 ],
        [0.48198977, 0.51097345, 0.51572204, 0.5250942 , 0.48652178,
         0.50853   ],
        [0.48230323, 0.51053846, 0.5161599 , 0.5254187 , 0.48503882,
         0.50878364]], dtype=float32),
 array([0, 0, 0, ..., 0, 0, 0]))

In [21]:
train_dataset[0][0].shape

(82930, 6)

In [22]:
train_dataset[0][1].shape

(82930,)

In [23]:
# count the different values in train_dataset[0][1]
import numpy as np
np.unique(train_dataset[0][1], return_counts=True)

(array([0, 1]), array([68170, 14760]))

In [16]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Example data
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Fit the scaler to the data and transform it
scaled_data = scaler.fit_transform(data)

print("Original data:")
print(data)

print("\nScaled data:")
print(scaled_data)

Original data:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Scaled data:
[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]


In [17]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Example data
data = np.array([[[0, 0, 0, 0, 0, 0],
                  [1, 2, 3, 4, 5, 6],
                  [7, 8, 9, 10, 11, 12]],
                 [[0, 0, 0, 0, 0, 0],
                  [13, 14, 15, 16, 17, 18],
                  [19, 20, 21, 22, 23, 24]]])

num_items, max_seq_len, _ = data.shape
max_seq_len -= 1

# Flatten the accelerometer data (first 3 columns after the first row)
acc_flat = data[:, 1:, :3].reshape(num_items * max_seq_len * 3, 1)

# Initialize the MinMaxScaler
acc_scaler = MinMaxScaler()

# Fit the scaler to the data and transform it
acc_flat = acc_scaler.fit_transform(acc_flat)

# Reshape the scaled data back to the original shape
data[:, 1:, :3] = acc_flat.reshape(num_items, max_seq_len, 3)

print("Scaled data:")
print(data)

Scaled data:
[[[ 0  0  0  0  0  0]
  [ 0  0  0  4  5  6]
  [ 0  0  0 10 11 12]]

 [[ 0  0  0  0  0  0]
  [ 0  0  0 16 17 18]
  [ 0  0  1 22 23 24]]]
